### ISSUE TITLE
Either use Alamofire or build our own simple "Networking" library

### ISSUE THREAD

**Issue by ejmartin504** [CondeNast/user-platform-ios-sdk#5]
We should make a decision: use Alamofire, or use our own internal "networking" library that we include in CondeKit.

I'm leaning towards Alamofire at this point. @biku?

**Comment by biku** [comment]
Lets go for alamofire.

On May 3, 2017, at 1:56 PM, Teddy Martin <notifications@github.com<mailto:notifications@github.com>> wrote:


We should make a decision: use Alamofire, or use our own internal "networking" library that we include in CondeKit.

I'm leaning towards Alamofire at this point. @biku<https://github.com/biku>?

**Comment by ejmartin504** [comment]
Sounds good. I've already started using it in #7
